require("./at.test.js");
require("./chart-at.test.js");
require("./concat.test.js");
require("./ends-with.test.js");
require("./includes.test.js");
require("./index-of.test.js");
require("./repeat.test.js");
require("./starts-with.test.js");
require("./to-lower-case.test.js");